package forge

import (
	"errors"
	"fmt"
	"strings"
)

// Non-destructive save_script guard.
//
// Background (live-confirmed bug): triggers.save_script regenerated a 4361-byte
// codegen war3map.lua straight over a 51908-byte hand-authored war3map.lua with
// no backup. The codegen is Lua-only and only knows how to lower GUI triggers;
// a hand-rolled script map (or any map whose war3map.lua was written by hand /
// by World Editor) is silently destroyed.
//
// The fix keys off a fact already true in the codebase: GenerateLuaScript()
// always emits CodegenMarkerLine as the very first line of its output. So any
// existing war3map.lua that does NOT start with that line was NOT produced by
// wc3-forge's codegen and must be treated as precious.
//
// Behavior:
//   - existing file is codegen-owned (first line == CodegenMarkerLine) → overwrite
//     freely (the normal regenerate path).
//   - existing file is preserve-marked (PreserveScriptMarker) → GenerateTriggerScript
//     already returns ErrPreserveScript; we never reach the write.
//   - existing file is hand-authored / unknown origin → DO NOT silently clobber.
//     SaveTriggerScriptGuarded(false) refuses with ErrScriptNotCodegen; the
//     caller must pass overwrite=true to proceed. EITHER WAY, before any
//     overwrite of a non-codegen file we first write a .bak sidecar so the
//     original bytes are recoverable.
//   - no existing file → write normally (nothing to clobber).

// CodegenMarkerLine is the first line GenerateLuaScript emits. Kept here (not
// imported from triggers_codegen.go) so the guard owns its own contract; a test
// asserts the generator still emits it so the two can't silently drift.
const CodegenMarkerLine = "-- generated by wc3-forge"

// ScriptBackupSuffix is appended to war3map.lua when the guard backs up a
// non-codegen file before overwriting it.
const ScriptBackupSuffix = ".bak"

// ErrScriptNotCodegen is returned by SaveTriggerScriptGuarded(overwrite=false)
// when the existing war3map.lua was not produced by wc3-forge's codegen, so the
// caller has a chance to bail out instead of destroying hand-authored Lua.
var ErrScriptNotCodegen = errors.New(
	"war3map.lua was not generated by wc3-forge (no \"" + CodegenMarkerLine + "\" marker) — " +
		"regenerating would overwrite hand-authored script; pass overwrite=true to proceed (a " +
		"war3map.lua" + ScriptBackupSuffix + " backup is written first)")

// firstLine returns the first line of b (without the trailing newline),
// trimmed of surrounding whitespace. Empty input yields "".
func firstLine(b []byte) string {
	s := string(b)
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		s = s[:i]
	}
	return strings.TrimSpace(s)
}

// looksLikeCodegen reports whether the bytes look like wc3-forge codegen output
// (first non-blank concern is the marker line).
func looksLikeCodegen(b []byte) bool {
	return firstLine(b) == CodegenMarkerLine
}

// SaveTriggerScriptGuarded is the non-destructive wrapper around
// SaveTriggerScript. It inspects the existing war3map.lua before regenerating:
//
//   - if the file is absent or codegen-owned, it regenerates + writes normally.
//   - if the file is hand-authored and overwrite is false, it returns
//     ErrScriptNotCodegen WITHOUT writing anything.
//   - if the file is hand-authored and overwrite is true, it copies the current
//     bytes to war3map.lua.bak first, then regenerates + writes.
//
// Returns the number of bytes written to war3map.lua on success.
func (s *Session) SaveTriggerScriptGuarded(overwrite bool) (int, error) {
	// Snapshot the source under the lock; everything else is best-effort I/O
	// that GenerateTriggerScript/SaveTriggerScript already perform lock-free.
	s.mu.RLock()
	src := s.source
	loaded := s.loaded
	s.mu.RUnlock()
	if !loaded {
		return 0, fmt.Errorf("no map loaded")
	}
	if src == nil {
		return 0, fmt.Errorf("no source for writing")
	}

	// Inspect the existing file. A read error other than "absent" is surfaced
	// so we never overwrite based on a half-read inspection.
	existing, ok, err := src.read("war3map.lua")
	if err != nil {
		return 0, fmt.Errorf("inspect existing war3map.lua: %w", err)
	}

	if ok && len(existing) > 0 && !looksLikeCodegen(existing) {
		// Hand-authored / unknown-origin script. Never silently clobber.
		if !overwrite {
			return 0, ErrScriptNotCodegen
		}
		// Backup the precious bytes before we regenerate over them. The backup
		// failing is fatal — better to refuse the save than to lose the file.
		if err := src.write("war3map.lua"+ScriptBackupSuffix, existing); err != nil {
			return 0, fmt.Errorf("backup hand-authored war3map.lua before overwrite: %w", err)
		}
	}

	// Codegen-owned, absent, or backed-up-and-cleared-to-overwrite: regenerate.
	// SaveTriggerScript honors ErrLuaOnly + ErrPreserveScript itself.
	return s.SaveTriggerScript()
}
