// Package forge — JASS codegen for the Trigger Editor (native-JASS support).
//
// Sibling of triggers_codegen.go (the Lua emitter). Both are ports of HiveWE's
// convert_gui_to_jass (src/base/triggers/gui.cpp) + MapScriptWriter
// (triggers.ixx) + generate_map_script (map_script.cpp). The Lua file REDUCES
// HiveWE's JASS output to Lua syntax; this file keeps it as JASS. Because the
// Lua emitter is a line-by-line port of the original JASS generator, this file
// is mostly the Lua emitter with the reductions reversed:
//
//	Lua                         JASS
//	------------------------    ----------------------------
//	top-level `x = nil`         `globals ... endglobals` block w/ typed decls
//	`Foo(a, b)`  (statement)    `call Foo(a, b)`
//	`x = y`      (statement)    `set x = y`
//	`if c then .. else .. end`  `if (c) then .. else .. endif`
//	`while c do .. end`         `loop .. exitwhen .. .. endloop`
//	`a ~= b`                    `a != b`
//	`(a .. b)`  (string concat) `(a + b)`
//	`FourCC("xxxx")`            `'xxxx'`  (rawcode literal)
//	`nil`                       `null`
//	`-- comment`                `// comment`
//	`function f() .. end`       `function f takes nothing returns T .. endfunction`
//
// A genuine WIN over the Lua path: a JASS map's custom-script actions
// (CustomScriptCode), GlobalJASS header, and hand-rolled Map Header are ALL
// already JASS. The Lua codegen inlines them verbatim into a .lua file, which
// is broken JASS-in-Lua; the JASS codegen inlines them into a .j file where
// they belong. That is the core reason native-JASS support exists.
//
// Like the Lua file, this is pure over its inputs: it takes the parsed wtg +
// custom_text + units/doodads + TriggerData + w3i and returns a string. File
// I/O happens in session.go / triggers.go.
//
// Shared, language-agnostic helpers (scrapeNamedRefs, sortedRefs,
// sanitizeIdent, radToDeg, pickSkinID, pickDoodadSkinID, isFourCCType,
// CodegenInputs) live in triggers_codegen.go and are reused here directly.
package forge

import (
	"fmt"
	"strings"

	"github.com/StephenSHorton/wc3-forge/internal/formats/wtg"
)

// JASSCodegenMarkerLine is the first line GenerateJASSScript emits — the JASS
// analogue of CodegenMarkerLine. Used by the save guard to recognize
// codegen-owned war3map.j so a regenerate doesn't clobber hand-authored JASS.
const JASSCodegenMarkerLine = "// generated by wc3-forge"

// PreserveScriptMarkerJASS is the JASS-comment guard string that, at the top
// of war3map.j, tells the codegen to refuse regeneration (preserve hand
// edits). JASS analogue of PreserveScriptMarker.
const PreserveScriptMarkerJASS = "//WC3FORGE_PRESERVE_SCRIPT"

// GenerateJASSScript is the native-JASS entry point. Returns war3map.j source
// + nil on success. Refuses generation when Info.Lua is true (that's a Lua
// map — caller should use GenerateLuaScript). Output structure mirrors the Lua
// emitter's order (which itself mirrors HiveWE map_script.cpp L811-846), in
// JASS syntax.
func GenerateJASSScript(in CodegenInputs) (string, error) {
	if in.Info != nil && in.Info.Lua {
		return "", fmt.Errorf("GenerateJASSScript called on a Lua map — use GenerateLuaScript")
	}
	if in.Triggers == nil {
		in.Triggers = &wtg.Triggers{}
	}
	if in.TD == nil {
		return "", fmt.Errorf("GenerateJASSScript: TriggerData snapshot is required")
	}

	cg := &jassCodegen{in: in}

	// Phase A — concat every non-comment, enabled trigger's source. custom_text
	// (script triggers / hand-edited GUI) wins; empty means "GUI, lower from
	// ECAs". Identical to the Lua path.
	var triggerScript strings.Builder
	var initTriggers []string
	for i := range in.Triggers.Triggers {
		tr := &in.Triggers.Triggers[i]
		if tr.IsComment || !tr.IsEnabled {
			continue
		}
		ct := tr.CustomText
		if in.CustomTexts != nil {
			if v, ok := in.CustomTexts[tr.ID]; ok {
				ct = v
			}
		}
		if ct != "" {
			triggerScript.WriteString(ct)
			triggerScript.WriteByte('\n')
			continue
		}
		triggerScript.WriteString(cg.convertTriggerToJASS(tr, &initTriggers))
	}

	// Phase B — scrape gg_unit_/gg_dest_ refs (shared helper).
	unitVars, destVars := scrapeNamedRefs(triggerScript.String())

	// Phase C — emit.
	cg.script.Grow(1 << 16)
	cg.script.WriteString(JASSCodegenMarkerLine + "\n")
	cg.script.WriteString("// DO NOT EDIT (use Trigger Editor)\n")
	cg.script.WriteString("// To preserve hand-edits, prepend a line: " + PreserveScriptMarkerJASS + "\n\n")

	cg.emitGlobals(unitVars, destVars)
	cg.emitInitGlobals()
	cg.emitItemTables()
	cg.emitInitSounds()
	cg.emitCreateAllDestructables(destVars)
	cg.emitCreateAllItems()
	cg.emitCreateAllUnits(unitVars)
	cg.emitCreateRegions()
	cg.emitCreateCameras()

	if strings.TrimSpace(in.GlobalJASS) != "" {
		cg.script.WriteString("\n// global custom-script header (from war3map.wct GlobalJASS)\n")
		cg.script.WriteString(in.GlobalJASS)
		if !strings.HasSuffix(in.GlobalJASS, "\n") {
			cg.script.WriteByte('\n')
		}
		cg.script.WriteByte('\n')
	}

	cg.script.WriteString("\n// triggers\n")
	cg.script.WriteString(triggerScript.String())

	cg.emitInitCustomTriggers()
	cg.emitRunInitializationTriggers(initTriggers)
	cg.emitInitCustomPlayerSlots()
	cg.emitInitCustomTeams()
	cg.emitInitAllyPriorities()
	cg.emitVJASSInitLibs()
	cg.emitMain()
	cg.emitConfig()

	return cg.script.String(), nil
}

// jassCodegen — emitter state. Mirrors luaCodegen.
type jassCodegen struct {
	in         CodegenInputs
	script     strings.Builder
	fnCounter  int
	preActions strings.Builder // per-trigger pre-action sink (helper functions)
}

// fnName mints a JASS-safe per-trigger helper-function name.
func (c *jassCodegen) fnName(trigger string) string {
	c.fnCounter++
	return fmt.Sprintf("Trig_%s_Wc3Forge%d", sanitizeIdent(trigger), c.fnCounter-1)
}

// ---------------------------------------------------------------------------
// JASS-specific small helpers.
// ---------------------------------------------------------------------------

// escapeJASSString escapes a string literal for inclusion in JASS source.
// JASS supports \", \\, \n, \r, \t — UTF-8 bytes pass through verbatim (unlike
// Go's %q which would emit \uXXXX). Mirrors escapeLuaString's intent.
func escapeJASSString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\r", `\r`, "\t", `\t`)
	return r.Replace(s)
}

// jassTypeFor returns the JASS type for a GUI variable type. BaseType walks
// the TriggerTypes alias chain to the atomic type, which for GUI types is the
// JASS storage type (unitcode → integer, unit → unit, abilcode → integer,
// StringExt → string, …). Empty falls back to integer.
func (c *jassCodegen) jassTypeFor(guiType string) string {
	base := c.in.TD.BaseType(guiType)
	if base == "" {
		return "integer"
	}
	return base
}

// jassDefaultForType returns the globals-block initializer for a scalar JASS
// type. Matches World Editor's generated globals block (primitives get a
// concrete zero, handles get null).
func jassDefaultForType(base string) string {
	switch base {
	case "integer":
		return "0"
	case "real":
		return "0.0"
	case "boolean":
		return "false"
	case "string":
		return `""`
	default:
		return "null"
	}
}

// jassCall prefixes a function-call expression with "call " when it is being
// emitted in statement position (addCall==true). Expression contexts pass
// addCall==false and get the bare call.
func jassCall(addCall bool, expr string) string {
	if addCall {
		return "call " + expr
	}
	return expr
}

// ---------------------------------------------------------------------------
// Phase C emitters — JASS.
// ---------------------------------------------------------------------------

// emitGlobals writes the single `globals ... endglobals` block: udg_ vars,
// gg_rct_/gg_cam_/gg_trg_, and the referenced gg_unit_/gg_dest_ named handles.
func (c *jassCodegen) emitGlobals(units, dests map[string]string) {
	t := c.in.Triggers
	c.script.WriteString("globals\n")

	for _, v := range t.Variables {
		typ := c.jassTypeFor(v.Type)
		if v.IsArray {
			c.script.WriteString(fmt.Sprintf("\t%s array udg_%s\n", typ, v.Name))
		} else {
			c.script.WriteString(fmt.Sprintf("\t%s udg_%s = %s\n", typ, v.Name, jassDefaultForType(typ)))
		}
	}
	if c.in.Regions != nil {
		for _, r := range c.in.Regions.Regions {
			c.script.WriteString(fmt.Sprintf("\trect gg_rct_%s = null\n", sanitizeIdent(r.Name)))
		}
	}
	if c.in.Cameras != nil {
		for _, cm := range c.in.Cameras.Cameras {
			c.script.WriteString(fmt.Sprintf("\tcamerasetup gg_cam_%s = null\n", sanitizeIdent(cm.Name)))
		}
	}
	for _, tr := range t.Triggers {
		if tr.IsComment || !tr.IsEnabled {
			continue
		}
		c.script.WriteString(fmt.Sprintf("\ttrigger gg_trg_%s = null\n", sanitizeIdent(tr.Name)))
	}
	for _, num := range sortedRefs(units) {
		c.script.WriteString(fmt.Sprintf("\tunit gg_unit_%s_%s = null\n", units[num], num))
	}
	for _, num := range sortedRefs(dests) {
		c.script.WriteString(fmt.Sprintf("\tdestructable gg_dest_%s_%s = null\n", dests[num], num))
	}
	c.script.WriteString("endglobals\n\n")
}

// emitInitGlobals writes InitGlobals: per-variable assignments resolving
// initial values via TriggerParams presets / TriggerTypeDefaults, JASS arrays
// looped over array_size. Mirrors the Lua emitInitGlobals.
func (c *jassCodegen) emitInitGlobals() {
	td := c.in.TD
	t := c.in.Triggers

	var body strings.Builder
	needLoopVar := false
	for _, v := range t.Variables {
		base := td.BaseType(v.Type)
		var valueExpr string
		hasInit := false
		if v.IsInitialized && v.InitialValue != "" {
			hasInit = true
			if presetRows, ok := td.Sections["TriggerParams"]; ok {
				if toks, ok := presetRows[v.InitialValue]; ok && len(toks) >= 3 {
					valueExpr = toks[2]
				}
			}
			if valueExpr == "" {
				if base == "string" {
					valueExpr = `"` + escapeJASSString(v.InitialValue) + `"`
				} else {
					valueExpr = v.InitialValue
				}
			}
		}
		if !hasInit {
			if defs, ok := td.Sections["TriggerTypeDefaults"]; ok {
				if toks, ok := defs[base]; ok && len(toks) > 0 && toks[0] != "" {
					valueExpr = toks[0]
				}
			}
			if valueExpr == "" {
				continue
			}
		}
		if v.IsArray {
			needLoopVar = true
			size := v.ArraySize
			if size <= 0 {
				size = 1
			}
			body.WriteString("\tset i = 0\n")
			body.WriteString("\tloop\n")
			body.WriteString(fmt.Sprintf("\t\texitwhen i > %d\n", size))
			body.WriteString(fmt.Sprintf("\t\tset udg_%s[i] = %s\n", v.Name, valueExpr))
			body.WriteString("\t\tset i = i + 1\n")
			body.WriteString("\tendloop\n")
		} else {
			body.WriteString(fmt.Sprintf("\tset udg_%s = %s\n", v.Name, valueExpr))
		}
	}

	c.script.WriteString("function InitGlobals takes nothing returns nothing\n")
	if needLoopVar {
		c.script.WriteString("\tlocal integer i = 0\n")
	}
	c.script.WriteString(body.String())
	c.script.WriteString("endfunction\n\n")
}

// emitCreateAllUnits — placed-unit creation in JASS. Mirrors the Lua emitter
// (BlzCreateUnitWithSkin, life/mana, hero level/stats, acquire range,
// abilities, inventory, item-drop trigger wiring) with set/call prefixes and
// 'xxxx' rawcodes.
func (c *jassCodegen) emitCreateAllUnits(unitVars map[string]string) {
	c.script.WriteString("function CreateAllUnits takes nothing returns nothing\n")
	c.script.WriteString("\tlocal unit u\n\tlocal integer unitID\n\tlocal trigger t\n\tlocal real life\n")
	if c.in.Units == nil || c.in.Terrain == nil {
		c.script.WriteString("endfunction\n\n")
		return
	}
	offset := c.in.Terrain.CenterOffset
	for _, e := range c.in.Units.Entities {
		if e.TypeID == "sloc" {
			continue
		}
		ref := "u"
		num := fmt.Sprintf("%04d", e.CreationNumber)
		if _, ok := unitVars[num]; ok {
			ref = fmt.Sprintf("gg_unit_%s_%s", e.TypeID, num)
		}
		c.script.WriteString(fmt.Sprintf(
			"\tset %s = BlzCreateUnitWithSkin(Player(%d), '%s', %.4f, %.4f, %.4f, '%s')\n",
			ref, e.Player,
			e.TypeID,
			e.Position[0]*128.0+offset[0],
			e.Position[1]*128.0+offset[1],
			radToDeg(e.Rotation),
			pickSkinID(e),
		))
		if e.HitPointsPct != -1 {
			c.script.WriteString(fmt.Sprintf("\tset life = GetUnitState(%s, UNIT_STATE_LIFE)\n", ref))
			c.script.WriteString(fmt.Sprintf("\tcall SetUnitState(%s, UNIT_STATE_LIFE, %f * life)\n", ref, float32(e.HitPointsPct)/100.0))
		}
		if e.ManaPct != -1 {
			c.script.WriteString(fmt.Sprintf("\tcall SetUnitState(%s, UNIT_STATE_MANA, %d)\n", ref, e.ManaPct))
		}
		if e.HeroLevel > 1 {
			c.script.WriteString(fmt.Sprintf("\tcall SetHeroLevel(%s, %d, false)\n", ref, e.HeroLevel))
		}
		if e.HeroStr != 0 {
			c.script.WriteString(fmt.Sprintf("\tcall SetHeroStr(%s, %d, true)\n", ref, e.HeroStr))
		}
		if e.HeroAgi != 0 {
			c.script.WriteString(fmt.Sprintf("\tcall SetHeroAgi(%s, %d, true)\n", ref, e.HeroAgi))
		}
		if e.HeroInt != 0 {
			c.script.WriteString(fmt.Sprintf("\tcall SetHeroInt(%s, %d, true)\n", ref, e.HeroInt))
		}
		if e.TargetAcquisition != -1 {
			r := e.TargetAcquisition
			if r == -2 {
				r = 200
			}
			c.script.WriteString(fmt.Sprintf("\tcall SetUnitAcquireRange(%s, %f)\n", ref, r))
		}
		for _, j := range e.AbilityModifications {
			for k := uint32(0); k < j.Level; k++ {
				c.script.WriteString(fmt.Sprintf("\tcall SelectHeroSkill(%s, '%s')\n", ref, j.AbilityID))
			}
		}
		for _, item := range e.Inventory {
			c.script.WriteString(fmt.Sprintf("\tcall UnitAddItemToSlotById(%s, '%s', %d)\n", ref, item.ItemID, item.Slot))
		}
		if len(e.ItemDrops) > 0 {
			c.script.WriteString("\tset t = CreateTrigger()\n")
			c.script.WriteString(fmt.Sprintf("\tcall TriggerRegisterUnitEvent(t, %s, EVENT_UNIT_DEATH)\n", ref))
			c.script.WriteString(fmt.Sprintf("\tcall TriggerRegisterUnitEvent(t, %s, EVENT_UNIT_CHANGE_OWNER)\n", ref))
			c.script.WriteString(fmt.Sprintf("\tcall TriggerAddAction(t, function UnitItemDrops_%d)\n", e.CreationNumber))
		}
	}
	c.script.WriteString("endfunction\n\n")
}

// emitCreateAllItems — placeholder (matches Lua: items live on the same
// Entities slice without a SLK classifier, so we emit the empty function the
// runtime's main() expects).
func (c *jassCodegen) emitCreateAllItems() {
	c.script.WriteString("function CreateAllItems takes nothing returns nothing\nendfunction\n\n")
}

// emitCreateAllDestructables — placed-doodad creation in JASS.
func (c *jassCodegen) emitCreateAllDestructables(destVars map[string]string) {
	c.script.WriteString("function CreateAllDestructables takes nothing returns nothing\n")
	c.script.WriteString("\tlocal destructable d\n\tlocal trigger t\n\tlocal real life\n")
	if c.in.Doodads == nil || c.in.Terrain == nil {
		c.script.WriteString("endfunction\n\n")
		return
	}
	offset := c.in.Terrain.CenterOffset
	for _, d := range c.in.Doodads.Doodads {
		id := "d"
		num := fmt.Sprintf("%d", d.CreationNumber)
		if _, ok := destVars[num]; ok {
			id = fmt.Sprintf("gg_dest_%s_%s", d.TypeID, num)
		}
		if id == "d" && len(d.ItemDrops) == 0 && d.MapItemTable == -1 {
			continue
		}
		c.script.WriteString(fmt.Sprintf(
			"\tset %s = BlzCreateDestructableZWithSkin('%s', %.4f, %.4f, %.4f, %.4f, %f, %d, '%s')\n",
			id, d.TypeID,
			d.Position[0]*128.0+offset[0],
			d.Position[1]*128.0+offset[1],
			d.Position[2]*128.0,
			radToDeg(d.Rotation),
			d.Scale[0],
			d.Variation,
			pickDoodadSkinID(d),
		))
		if d.Life != 100 {
			c.script.WriteString(fmt.Sprintf("\tset life = GetDestructableLife(%s)\n", id))
			c.script.WriteString(fmt.Sprintf("\tcall SetDestructableLife(%s, %f * life)\n", id, float32(d.Life)/100.0))
		}
		if len(d.ItemDrops) > 0 {
			c.script.WriteString("\tset t = CreateTrigger()\n")
			c.script.WriteString(fmt.Sprintf("\tcall TriggerRegisterDeathEvent(t, %s)\n", id))
			c.script.WriteString("\tcall TriggerAddAction(t, function SaveDyingWidget)\n")
			c.script.WriteString(fmt.Sprintf("\tcall TriggerAddAction(t, function DoodadItemDrops_%d)\n", d.CreationNumber))
		} else if d.MapItemTable != -1 {
			c.script.WriteString("\tset t = CreateTrigger()\n")
			c.script.WriteString(fmt.Sprintf("\tcall TriggerRegisterDeathEvent(t, %s)\n", id))
			c.script.WriteString("\tcall TriggerAddAction(t, function SaveDyingWidget)\n")
			c.script.WriteString(fmt.Sprintf("\tcall TriggerAddAction(t, function ItemTable_%d)\n", d.MapItemTable))
		}
	}
	c.script.WriteString("endfunction\n\n")
}

// emitCreateRegions — CreateRegions in JASS.
func (c *jassCodegen) emitCreateRegions() {
	c.script.WriteString("function CreateRegions takes nothing returns nothing\n")
	c.script.WriteString("\tlocal weathereffect we\n")
	if c.in.Regions == nil {
		c.script.WriteString("endfunction\n\n")
		return
	}
	for _, r := range c.in.Regions.Regions {
		name := sanitizeIdent(r.Name)
		l, rt := r.Left, r.Right
		if l > rt {
			l, rt = rt, l
		}
		b, tp := r.Bottom, r.Top
		if b > tp {
			b, tp = tp, b
		}
		c.script.WriteString(fmt.Sprintf("\tset gg_rct_%s = Rect(%f, %f, %f, %f)\n", name, l, b, rt, tp))
		if r.WeatherID != "" && r.WeatherID != "\x00\x00\x00\x00" {
			c.script.WriteString(fmt.Sprintf("\tset we = AddWeatherEffect(gg_rct_%s, '%s')\n", name, r.WeatherID))
			c.script.WriteString("\tcall EnableWeatherEffect(we, true)\n")
		}
	}
	c.script.WriteString("endfunction\n\n")
}

// emitCreateCameras — CreateCameras in JASS.
func (c *jassCodegen) emitCreateCameras() {
	c.script.WriteString("function CreateCameras takes nothing returns nothing\n")
	if c.in.Cameras == nil {
		c.script.WriteString("endfunction\n\n")
		return
	}
	for _, cm := range c.in.Cameras.Cameras {
		name := sanitizeIdent(cm.Name)
		c.script.WriteString(fmt.Sprintf("\tset gg_cam_%s = CreateCameraSetup()\n", name))
		c.script.WriteString(fmt.Sprintf("\tcall CameraSetupSetField(gg_cam_%s, CAMERA_FIELD_ZOFFSET, %f, 0.0)\n", name, cm.ZOffset))
		c.script.WriteString(fmt.Sprintf("\tcall CameraSetupSetField(gg_cam_%s, CAMERA_FIELD_ROTATION, %f, 0.0)\n", name, cm.Rotation))
		c.script.WriteString(fmt.Sprintf("\tcall CameraSetupSetField(gg_cam_%s, CAMERA_FIELD_ANGLE_OF_ATTACK, %f, 0.0)\n", name, cm.AngleOfAttack))
		c.script.WriteString(fmt.Sprintf("\tcall CameraSetupSetField(gg_cam_%s, CAMERA_FIELD_TARGET_DISTANCE, %f, 0.0)\n", name, cm.Distance))
		c.script.WriteString(fmt.Sprintf("\tcall CameraSetupSetField(gg_cam_%s, CAMERA_FIELD_ROLL, %f, 0.0)\n", name, cm.Roll))
		c.script.WriteString(fmt.Sprintf("\tcall CameraSetupSetField(gg_cam_%s, CAMERA_FIELD_FIELD_OF_VIEW, %f, 0.0)\n", name, cm.FOV))
		c.script.WriteString(fmt.Sprintf("\tcall CameraSetupSetField(gg_cam_%s, CAMERA_FIELD_FARZ, %f, 0.0)\n", name, cm.FarZ))
		c.script.WriteString(fmt.Sprintf("\tcall CameraSetupSetField(gg_cam_%s, CAMERA_FIELD_NEARZ, %f, 0.0)\n", name, cm.NearZ))
		c.script.WriteString(fmt.Sprintf("\tcall CameraSetupSetDestPosition(gg_cam_%s, %f, %f, 0.0)\n", name, cm.TargetX, cm.TargetY))
	}
	c.script.WriteString("endfunction\n\n")
}

// emitInitSounds — empty placeholder (sounds not parsed yet).
func (c *jassCodegen) emitInitSounds() {
	c.script.WriteString("function InitSounds takes nothing returns nothing\nendfunction\n\n")
}

// emitItemTables — per-entity item-drop tables + map-level ItemTable_<n> in
// JASS. Mirrors the Lua emitItemTables shape.
func (c *jassCodegen) emitItemTables() {
	if c.in.Info != nil {
		for _, t := range c.in.Info.RandomItemTables {
			c.script.WriteString(fmt.Sprintf("function ItemTable_%d takes nothing returns nothing\n", t.CreationNumber))
			c.script.WriteString("\tlocal widget trigWidget = null\n\tlocal unit trigUnit = null\n\tlocal integer itemID = 0\n\tlocal boolean canDrop = true\n")
			c.script.WriteString("\tset trigWidget = bj_lastDyingWidget\n")
			c.script.WriteString("\tif (trigWidget == null) then\n")
			c.script.WriteString("\t\tset trigUnit = GetTriggerUnit()\n")
			c.script.WriteString("\tendif\n")
			c.script.WriteString("\tif not(trigUnit == null) then\n")
			c.script.WriteString("\t\tset canDrop = not IsUnitHidden(trigUnit)\n")
			c.script.WriteString("\t\tif (canDrop and not(GetChangingUnit() == null)) then\n")
			c.script.WriteString("\t\t\tset canDrop = (GetChangingUnitPrevOwner() == Player(PLAYER_NEUTRAL_AGGRESSIVE))\n")
			c.script.WriteString("\t\tendif\n")
			c.script.WriteString("\tendif\n")
			c.script.WriteString("\tif (canDrop) then\n")
			for _, set := range t.ItemSets {
				c.script.WriteString("\t\tcall RandomDistReset()\n")
				for _, item := range set.Items {
					emitItemTableEntryJASS(&c.script, "\t\t", int(item.Chance), item.ID)
				}
				c.script.WriteString("\t\tset itemID = RandomDistChoose()\n")
				c.script.WriteString("\t\tif not(trigUnit == null) then\n\t\t\tcall UnitDropItem(trigUnit, itemID)\n\t\tendif\n")
				c.script.WriteString("\t\tif (trigUnit == null) then\n\t\t\tcall WidgetDropItem(trigWidget, itemID)\n\t\tendif\n")
			}
			c.script.WriteString("\tendif\n")
			c.script.WriteString("\tset bj_lastDyingWidget = null\n")
			c.script.WriteString("\tcall DestroyTrigger(GetTriggeringTrigger())\n")
			c.script.WriteString("endfunction\n\n")
		}
	}
	if c.in.Units != nil {
		for _, e := range c.in.Units.Entities {
			if len(e.ItemDrops) == 0 {
				continue
			}
			c.script.WriteString(fmt.Sprintf("function UnitItemDrops_%d takes nothing returns nothing\n", e.CreationNumber))
			c.script.WriteString("\tlocal widget trigWidget = null\n\tlocal unit trigUnit = null\n\tlocal integer itemID = 0\n\tlocal boolean canDrop = true\n")
			c.script.WriteString("\tset trigWidget = bj_lastDyingWidget\n")
			c.script.WriteString("\tif (trigWidget == null) then\n\t\tset trigUnit = GetTriggerUnit()\n\tendif\n")
			c.script.WriteString("\tif (canDrop) then\n")
			c.script.WriteString("\t\tcall RandomDistReset()\n")
			for _, item := range e.ItemDrops {
				emitItemTableEntryJASS(&c.script, "\t\t", int(item.Chance), item.ItemID)
			}
			c.script.WriteString("\t\tset itemID = RandomDistChoose()\n")
			c.script.WriteString("\t\tif not(trigUnit == null) then\n\t\t\tcall UnitDropItem(trigUnit, itemID)\n\t\tendif\n")
			c.script.WriteString("\tendif\n")
			c.script.WriteString("\tset bj_lastDyingWidget = null\n")
			c.script.WriteString("\tcall DestroyTrigger(GetTriggeringTrigger())\n")
			c.script.WriteString("endfunction\n\n")
		}
	}
	if c.in.Doodads != nil {
		for _, d := range c.in.Doodads.Doodads {
			if len(d.ItemDrops) == 0 {
				continue
			}
			c.script.WriteString(fmt.Sprintf("function DoodadItemDrops_%d takes nothing returns nothing\n", d.CreationNumber))
			c.script.WriteString("\tlocal widget trigWidget = null\n\tlocal integer itemID = 0\n")
			c.script.WriteString("\tset trigWidget = bj_lastDyingWidget\n")
			c.script.WriteString("\tcall RandomDistReset()\n")
			for _, item := range d.ItemDrops {
				emitItemTableEntryJASS(&c.script, "\t", int(item.Chance), item.ItemID)
			}
			c.script.WriteString("\tset itemID = RandomDistChoose()\n")
			c.script.WriteString("\tcall WidgetDropItem(trigWidget, itemID)\n")
			c.script.WriteString("\tset bj_lastDyingWidget = null\n")
			c.script.WriteString("\tcall DestroyTrigger(GetTriggeringTrigger())\n")
			c.script.WriteString("endfunction\n\n")
		}
	}
}

// emitItemTableEntryJASS writes one RandomDistAddItem call (JASS). The id may
// be a random-item placeholder (Y[i-o,Y]I/) → ChooseRandomItemEx. Mirrors the
// Lua emitItemTableEntry with rawcode 'xxxx' literals.
func emitItemTableEntryJASS(b *strings.Builder, indent string, chance int, id string) {
	if id == "" {
		b.WriteString(fmt.Sprintf("%scall RandomDistAddItem(-1, %d)\n", indent, chance))
		return
	}
	if len(id) == 4 && id[0] == 'Y' && id[2] == 'I' &&
		((id[1] >= 'i' && id[1] <= 'o') || id[1] == 'Y') {
		var itemType string
		switch id[1] {
		case 'i':
			itemType = "PERMANENT"
		case 'j':
			itemType = "CHARGED"
		case 'k':
			itemType = "POWERUP"
		case 'l':
			itemType = "ARTIFACT"
		case 'm':
			itemType = "PURCHASABLE"
		case 'n':
			itemType = "CAMPAIGN"
		case 'o':
			itemType = "MISCELLANEOUS"
		case 'Y':
			itemType = "ANY"
		}
		level := "-1"
		if id[3] != '/' {
			level = string(id[3])
		}
		b.WriteString(fmt.Sprintf("%scall RandomDistAddItem(ChooseRandomItemEx(ITEM_TYPE_%s, %s), %d)\n", indent, itemType, level, chance))
		return
	}
	b.WriteString(fmt.Sprintf("%scall RandomDistAddItem('%s', %d)\n", indent, id, chance))
}

// emitInitCustomTriggers — call each InitTrig_<name> stub.
func (c *jassCodegen) emitInitCustomTriggers() {
	c.script.WriteString("function InitCustomTriggers takes nothing returns nothing\n")
	for _, tr := range c.in.Triggers.Triggers {
		if tr.IsComment || !tr.IsEnabled {
			continue
		}
		c.script.WriteString(fmt.Sprintf("\tcall InitTrig_%s()\n", sanitizeIdent(tr.Name)))
	}
	c.script.WriteString("endfunction\n\n")
}

// emitRunInitializationTriggers — ConditionalTriggerExecute for each
// MapInitializationEvent-bound trigger.
func (c *jassCodegen) emitRunInitializationTriggers(initTriggers []string) {
	c.script.WriteString("function RunInitializationTriggers takes nothing returns nothing\n")
	for _, n := range initTriggers {
		c.script.WriteString(fmt.Sprintf("\tcall ConditionalTriggerExecute(%s)\n", n))
	}
	c.script.WriteString("endfunction\n\n")
}

// emitInitCustomPlayerSlots — per-player slot init from w3i (JASS).
func (c *jassCodegen) emitInitCustomPlayerSlots() {
	c.script.WriteString("function InitCustomPlayerSlots takes nothing returns nothing\n")
	if c.in.Info == nil {
		c.script.WriteString("endfunction\n\n")
		return
	}
	playerType := []string{"MAP_CONTROL_USER", "MAP_CONTROL_COMPUTER", "MAP_CONTROL_NEUTRAL", "MAP_CONTROL_RESCUABLE"}
	races := []string{"RACE_PREF_RANDOM", "RACE_PREF_HUMAN", "RACE_PREF_ORC", "RACE_PREF_UNDEAD", "RACE_PREF_NIGHTELF"}
	for idx, p := range c.in.Info.Players {
		pn := int(p.InternalNumber)
		typ := int(p.Type)
		race := int(p.Race)
		if typ < 0 || typ >= len(playerType) {
			typ = 0
		}
		if race < 0 || race >= len(races) {
			race = 0
		}
		c.script.WriteString(fmt.Sprintf("\tcall SetPlayerStartLocation(Player(%d), %d)\n", pn, idx))
		if p.FixedStartPosition != 0 || race == 0 {
			c.script.WriteString(fmt.Sprintf("\tcall ForcePlayerStartLocation(Player(%d), %d)\n", pn, idx))
		}
		c.script.WriteString(fmt.Sprintf("\tcall SetPlayerColor(Player(%d), ConvertPlayerColor(%d))\n", pn, pn))
		c.script.WriteString(fmt.Sprintf("\tcall SetPlayerRacePreference(Player(%d), %s)\n", pn, races[race]))
		c.script.WriteString(fmt.Sprintf("\tcall SetPlayerRaceSelectable(Player(%d), true)\n", pn))
		c.script.WriteString(fmt.Sprintf("\tcall SetPlayerController(Player(%d), %s)\n", pn, playerType[typ]))
	}
	c.script.WriteString("endfunction\n\n")
}

// emitInitCustomTeams — force/alliance/vision/control sharing (JASS).
func (c *jassCodegen) emitInitCustomTeams() {
	c.script.WriteString("function InitCustomTeams takes nothing returns nothing\n")
	if c.in.Info == nil {
		c.script.WriteString("endfunction\n\n")
		return
	}
	for i, f := range c.in.Info.Forces {
		for _, p := range c.in.Info.Players {
			if f.PlayerMasks&(1<<uint(p.InternalNumber)) != 0 {
				c.script.WriteString(fmt.Sprintf("\tcall SetPlayerTeam(Player(%d), %d)\n", p.InternalNumber, i))
				if f.Flags.AlliedVictory {
					c.script.WriteString(fmt.Sprintf("\tcall SetPlayerState(Player(%d), PLAYER_STATE_ALLIED_VICTORY, 1)\n", p.InternalNumber))
				}
			}
		}
		for _, j := range c.in.Info.Players {
			if f.PlayerMasks&(1<<uint(j.InternalNumber)) == 0 {
				continue
			}
			for _, k := range c.in.Info.Players {
				if f.PlayerMasks&(1<<uint(k.InternalNumber)) == 0 || j.InternalNumber == k.InternalNumber {
					continue
				}
				if f.Flags.Allied {
					c.script.WriteString(fmt.Sprintf("\tcall SetPlayerAllianceStateAllyBJ(Player(%d), Player(%d), true)\n", j.InternalNumber, k.InternalNumber))
				}
				if f.Flags.ShareVision {
					c.script.WriteString(fmt.Sprintf("\tcall SetPlayerAllianceStateVisionBJ(Player(%d), Player(%d), true)\n", j.InternalNumber, k.InternalNumber))
				}
				if f.Flags.ShareUnitControl {
					c.script.WriteString(fmt.Sprintf("\tcall SetPlayerAllianceStateControlBJ(Player(%d), Player(%d), true)\n", j.InternalNumber, k.InternalNumber))
				}
				if f.Flags.ShareAdvancedUnitControl {
					c.script.WriteString(fmt.Sprintf("\tcall SetPlayerAllianceStateFullControlBJ(Player(%d), Player(%d), true)\n", j.InternalNumber, k.InternalNumber))
				}
			}
		}
	}
	c.script.WriteString("endfunction\n\n")
}

// emitInitAllyPriorities — start-loc priorities (JASS).
func (c *jassCodegen) emitInitAllyPriorities() {
	c.script.WriteString("function InitAllyPriorities takes nothing returns nothing\n")
	if c.in.Info == nil {
		c.script.WriteString("endfunction\n\n")
		return
	}
	playerToStartLoc := map[int32]int{}
	current := 0
	for _, p := range c.in.Info.Players {
		playerToStartLoc[p.InternalNumber] = current
		current++
	}
	current = 0
	for _, p := range c.in.Info.Players {
		count := 0
		for _, j := range c.in.Info.Players {
			if p.InternalNumber == j.InternalNumber {
				continue
			}
			if p.AllyLowPriorities&(1<<uint(j.InternalNumber)) != 0 || p.AllyHighPriorities&(1<<uint(j.InternalNumber)) != 0 {
				count++
			}
		}
		c.script.WriteString(fmt.Sprintf("\tcall SetStartLocPrioCount(%d, %d)\n", current, count))
		idx := 0
		for _, j := range c.in.Info.Players {
			if p.InternalNumber == j.InternalNumber {
				continue
			}
			if p.AllyLowPriorities&(1<<uint(j.InternalNumber)) != 0 {
				c.script.WriteString(fmt.Sprintf("\tcall SetStartLocPrio(%d, %d, %d, MAP_LOC_PRIO_LOW)\n", current, idx, playerToStartLoc[j.InternalNumber]))
				idx++
			} else if p.AllyHighPriorities&(1<<uint(j.InternalNumber)) != 0 {
				c.script.WriteString(fmt.Sprintf("\tcall SetStartLocPrio(%d, %d, %d, MAP_LOC_PRIO_HIGH)\n", current, idx, playerToStartLoc[j.InternalNumber]))
				idx++
			}
		}
		current++
	}
	c.script.WriteString("endfunction\n\n")
}

// emitVJASSInitLibs — synthetic library/struct initializer (JASS). For a
// GUI-authored JASS map LibInits/StructInits are empty, so this is an empty
// function; it is emitted unconditionally so main()'s call site is stable.
func (c *jassCodegen) emitVJASSInitLibs() {
	c.script.WriteString("function _vjass_init_libs takes nothing returns nothing\n")
	seenLib := map[string]bool{}
	for _, lib := range c.in.LibInits {
		if seenLib[lib.Name] || lib.InitFunc == "" {
			continue
		}
		seenLib[lib.Name] = true
		c.script.WriteString(fmt.Sprintf("\tcall %s()\n", lib.InitFunc))
	}
	seenStruct := map[string]bool{}
	for _, st := range c.in.StructInits {
		if seenStruct[st.StructName] || st.InitMethod == "" {
			continue
		}
		seenStruct[st.StructName] = true
		c.script.WriteString(fmt.Sprintf("\tcall %s.%s()\n", st.StructName, st.InitMethod))
	}
	c.script.WriteString("endfunction\n\n")
}

// emitMain — main() in JASS.
func (c *jassCodegen) emitMain() {
	c.script.WriteString("function main takes nothing returns nothing\n")
	if c.in.Info != nil {
		i := c.in.Info
		c.script.WriteString(fmt.Sprintf(
			"\tcall SetCameraBounds(%f + GetCameraMargin(CAMERA_MARGIN_LEFT), %f + GetCameraMargin(CAMERA_MARGIN_BOTTOM), %f - GetCameraMargin(CAMERA_MARGIN_RIGHT), %f - GetCameraMargin(CAMERA_MARGIN_TOP), %f + GetCameraMargin(CAMERA_MARGIN_LEFT), %f - GetCameraMargin(CAMERA_MARGIN_TOP), %f - GetCameraMargin(CAMERA_MARGIN_RIGHT), %f + GetCameraMargin(CAMERA_MARGIN_BOTTOM))\n",
			i.CameraLeftBottom.X-512, i.CameraLeftBottom.Y-256,
			i.CameraRightTop.X+512, i.CameraRightTop.Y+256,
			i.CameraLeftTop.X-512, i.CameraLeftTop.Y+256,
			i.CameraRightBottom.X+512, i.CameraRightBottom.Y-256,
		))
	}
	c.script.WriteString("\tcall SetDayNightModels(\"\", \"\")\n")
	c.script.WriteString("\tcall NewSoundEnvironment(\"\")\n")
	c.script.WriteString("\tcall SetAmbientDaySound(\"\")\n")
	c.script.WriteString("\tcall SetAmbientNightSound(\"\")\n")
	c.script.WriteString("\tcall SetMapMusic(\"Music\", true, 0)\n")
	c.script.WriteString("\tcall InitSounds()\n")
	c.script.WriteString("\tcall CreateRegions()\n")
	c.script.WriteString("\tcall CreateCameras()\n")
	c.script.WriteString("\tcall CreateAllDestructables()\n")
	c.script.WriteString("\tcall CreateAllItems()\n")
	c.script.WriteString("\tcall CreateAllUnits()\n")
	c.script.WriteString("\tcall InitBlizzard()\n")
	c.script.WriteString("\tcall InitGlobals()\n")
	c.script.WriteString("\tcall _vjass_init_libs()\n")
	c.script.WriteString("\tcall InitCustomTriggers()\n")
	c.script.WriteString("\tcall RunInitializationTriggers()\n")
	c.script.WriteString("endfunction\n\n")
}

// emitConfig — config() in JASS.
func (c *jassCodegen) emitConfig() {
	c.script.WriteString("function config takes nothing returns nothing\n")
	if c.in.Info != nil {
		c.script.WriteString(fmt.Sprintf("\tcall SetMapName(\"%s\")\n", escapeJASSString(c.in.Info.Name)))
		c.script.WriteString(fmt.Sprintf("\tcall SetMapDescription(\"%s\")\n", escapeJASSString(c.in.Info.Description)))
		c.script.WriteString(fmt.Sprintf("\tcall SetPlayers(%d)\n", len(c.in.Info.Players)))
		c.script.WriteString(fmt.Sprintf("\tcall SetTeams(%d)\n", len(c.in.Info.Forces)))
		c.script.WriteString("\tcall SetGamePlacement(MAP_PLACEMENT_USE_MAP_SETTINGS)\n\n")
	}
	if c.in.Units != nil && c.in.Terrain != nil {
		offset := c.in.Terrain.CenterOffset
		for _, e := range c.in.Units.Entities {
			if e.TypeID == "sloc" {
				c.script.WriteString(fmt.Sprintf(
					"\tcall DefineStartLocation(%d, %f, %f)\n",
					e.Player, e.Position[0]*128+offset[0], e.Position[1]*128+offset[1],
				))
			}
		}
	}
	c.script.WriteString("\n\tcall InitCustomPlayerSlots()\n")
	if c.in.Info != nil && c.in.Info.Flags.CustomForces {
		c.script.WriteString("\tcall InitCustomTeams()\n")
	} else if c.in.Info != nil {
		for _, p := range c.in.Info.Players {
			c.script.WriteString(fmt.Sprintf("\tcall SetPlayerSlotAvailable(Player(%d), MAP_CONTROL_USER)\n", p.InternalNumber))
		}
		c.script.WriteString("\tcall InitGenericPlayerSlots()\n")
	}
	c.script.WriteString("\tcall InitAllyPriorities()\n")
	c.script.WriteString("endfunction\n")
}

// ---------------------------------------------------------------------------
// convertTriggerToJASS + convertECAToJASS + resolveParameterJASS — the magic
// ECAs land in convertECAToJASS. Mirrors the Lua trio with JASS syntax + the
// statement `call`/`set` prefixing the Lua path doesn't need.
// ---------------------------------------------------------------------------

// convertTriggerToJASS emits one trigger's worth of script: pre-actions, the
// optional condition function, the action function, and the InitTrig_<Name>
// stub. Mirrors convertTriggerToLua / HiveWE convert_gui_to_jass.
func (c *jassCodegen) convertTriggerToJASS(tr *wtg.Trigger, initTriggers *[]string) string {
	name := sanitizeIdent(tr.Name)
	triggerVar := "gg_trg_" + name
	actionName := "Trig_" + name + "_Actions"
	condName := "Trig_" + name + "_Conditions"

	c.preActions.Reset()

	var events strings.Builder
	var conditions strings.Builder
	var actions strings.Builder

	hasConditions := false
	for _, eca := range tr.ECAs {
		if !eca.Enabled {
			continue
		}
		switch eca.Type {
		case wtg.ECAEvent:
			if eca.Name == "MapInitializationEvent" {
				*initTriggers = append(*initTriggers, triggerVar)
				continue
			}
			var args []string
			for k, p := range eca.Parameters {
				typ := c.typeFor(eca.Name, k)
				val, _ := c.resolveParameter(&p, tr.Name, typ, false)
				if typ == "VarAsString_Real" {
					val = `"` + val + `"`
				}
				args = append(args, val)
			}
			argList := strings.Join(args, ", ")
			if argList != "" {
				events.WriteString(fmt.Sprintf("\tcall %s(%s, %s)\n", eca.Name, triggerVar, argList))
			} else {
				events.WriteString(fmt.Sprintf("\tcall %s(%s)\n", eca.Name, triggerVar))
			}
		case wtg.ECACondition:
			hasConditions = true
			cond, _ := c.convertECAToJASS(&eca, tr.Name, false)
			conditions.WriteString(fmt.Sprintf("\tif (not (%s)) then\n\t\treturn false\n\tendif\n", cond))
		case wtg.ECAAction:
			a, _ := c.convertECAToJASS(&eca, tr.Name, true)
			actions.WriteString("\t" + a + "\n")
		}
	}

	var out strings.Builder
	out.WriteString(c.preActions.String())
	if hasConditions {
		out.WriteString(fmt.Sprintf("function %s takes nothing returns boolean\n", condName))
		out.WriteString(conditions.String())
		out.WriteString("\treturn true\nendfunction\n\n")
	}
	out.WriteString(fmt.Sprintf("function %s takes nothing returns nothing\n", actionName))
	out.WriteString(actions.String())
	out.WriteString("endfunction\n\n")
	out.WriteString(fmt.Sprintf("function InitTrig_%s takes nothing returns nothing\n", name))
	out.WriteString(fmt.Sprintf("\tset %s = CreateTrigger()\n", triggerVar))
	out.WriteString(events.String())
	if hasConditions {
		out.WriteString(fmt.Sprintf("\tcall TriggerAddCondition(%s, Condition(function %s))\n", triggerVar, condName))
	}
	if !tr.InitiallyOn {
		out.WriteString(fmt.Sprintf("\tcall DisableTrigger(%s)\n", triggerVar))
	}
	out.WriteString(fmt.Sprintf("\tcall TriggerAddAction(%s, function %s)\n", triggerVar, actionName))
	out.WriteString("endfunction\n\n")
	return out.String()
}

// typeFor / scriptNameFor / baseTypeOf — TriggerData lookups. Identical logic
// to the luaCodegen methods (they only read c.in.TD); duplicated as jassCodegen
// methods so the two emitters stay independent.
func (c *jassCodegen) typeFor(name string, k int) string {
	td := c.in.TD
	if rows, ok := td.Sections["TriggerActions"]; ok {
		if toks, ok := rows[name]; ok && 1+k < len(toks) {
			return toks[1+k]
		}
	}
	if rows, ok := td.Sections["TriggerCalls"]; ok {
		if toks, ok := rows[name]; ok && 3+k < len(toks) {
			return toks[3+k]
		}
	}
	if rows, ok := td.Sections["TriggerEvents"]; ok {
		if toks, ok := rows[name]; ok && 1+k < len(toks) {
			return toks[1+k]
		}
	}
	if rows, ok := td.Sections["TriggerConditions"]; ok {
		if toks, ok := rows[name]; ok && 1+k < len(toks) {
			return toks[1+k]
		}
	}
	return ""
}

func (c *jassCodegen) scriptNameFor(name string) string {
	for _, sect := range []string{"TriggerActions", "TriggerCalls", "TriggerEvents", "TriggerConditions"} {
		if rows, ok := c.in.TD.Sections[sect]; ok {
			if toks, ok := rows["_"+name+"_ScriptName"]; ok && len(toks) > 0 {
				return toks[0]
			}
		}
	}
	return name
}

func (c *jassCodegen) baseTypeOf(typeName string) string {
	if c.in.TD == nil {
		return typeName
	}
	return c.in.TD.BaseType(typeName)
}

// resolveParameterJASS is the JASS port of resolveParameter. The only
// divergences from the Lua version: FourCC code types emit a 'xxxx' rawcode
// literal instead of FourCC("xxxx"), and sub-function calls recurse into
// convertECAToJASS.
func (c *jassCodegen) resolveParameter(p *wtg.Parameter, triggerName, expectedType string, addCall bool) (string, error) {
	switch p.Type {
	case wtg.ParamInvalid:
		return "", fmt.Errorf("invalid parameter type in trigger %q", triggerName)
	case wtg.ParamPreset:
		presetRows := c.in.TD.Sections["TriggerParams"]
		if presetRows == nil {
			return "", nil
		}
		toks := presetRows[p.Value]
		if len(toks) < 3 {
			return "", nil
		}
		presetType := toks[1]
		literal := toks[2]
		if c.baseTypeOf(presetType) == "string" {
			// Preset string literals use backtick as the quote placeholder.
			return strings.ReplaceAll(literal, "`", `"`), nil
		}
		if presetType == "timedlifebuffcode" || isFourCCType(expectedType) {
			// Normalize to a JASS rawcode literal: strip any quotes the data
			// carries, then wrap in single quotes.
			lit := strings.ReplaceAll(literal, "'", "")
			return "'" + lit + "'", nil
		}
		return literal, nil
	case wtg.ParamFunction:
		if p.HasSubParameter && p.SubParameter != nil {
			s, err := c.convertECAToJASS(p.SubParameter, triggerName, addCall)
			if err != nil {
				return "", err
			}
			return s, nil
		}
		return p.Value + "()", nil
	case wtg.ParamVariable:
		out := p.Value
		if !strings.HasPrefix(out, "gg_") {
			out = "udg_" + out
		}
		if p.IsArray && p.ArrayIndex != nil {
			ix, err := c.resolveParameter(p.ArrayIndex, triggerName, "integer", false)
			if err != nil {
				return "", err
			}
			out += "[" + ix + "]"
		}
		return out, nil
	case wtg.ParamString:
		base := c.baseTypeOf(expectedType)
		if base == "string" {
			return `"` + strings.ReplaceAll(p.Value, `\`, `\\`) + `"`, nil
		}
		if isFourCCType(expectedType) {
			return "'" + p.Value + "'", nil
		}
		return p.Value, nil
	}
	return "", nil
}

// convertECAToJASS lowers one ECA to a JASS expression-or-statement. addCall
// selects statement form (prepend `call `/`set `) vs expression form. This is
// the big switch over the magic ECA names, mirroring convertECAToLua with JASS
// syntax. Each branch corresponds 1:1 to the Lua branch so future agents
// diffing the two (or against HiveWE) see the correspondence.
func (c *jassCodegen) convertECAToJASS(eca *wtg.ECA, triggerName string, addCall bool) (string, error) {
	if !eca.Enabled {
		return "", nil
	}

	// IfThenElse — three-param if/then/else.
	if eca.Name == "IfThenElse" {
		fn := c.fnName(triggerName)
		condStr, _ := c.resolveParameter(&eca.Parameters[0], triggerName, c.typeFor(eca.Name, 0), false)
		thenStr, _ := c.resolveParameter(&eca.Parameters[1], triggerName, c.typeFor(eca.Name, 1), true)
		elseStr, _ := c.resolveParameter(&eca.Parameters[2], triggerName, c.typeFor(eca.Name, 2), true)
		fmt.Fprintf(&c.preActions, "function %s takes nothing returns boolean\n\treturn %s\nendfunction\n\n", fn, condStr)
		var b strings.Builder
		fmt.Fprintf(&b, "if (%s()) then\n\t%s\nelse\n\t%s\nendif", fn, thenStr, elseStr)
		return b.String(), nil
	}

	// IfThenElseMultiple — multi-child if/then/else.
	if eca.Name == "IfThenElseMultiple" {
		fn := c.fnName(triggerName)
		var conds []string
		for _, child := range eca.Children {
			if child.Type != wtg.ECACondition {
				continue
			}
			s, _ := c.convertECAToJASS(&child, triggerName, false)
			conds = append(conds, s)
		}
		fmt.Fprintf(&c.preActions, "function %s takes nothing returns boolean\n", fn)
		for _, cnd := range conds {
			fmt.Fprintf(&c.preActions, "\tif (not (%s)) then\n\t\treturn false\n\tendif\n", cnd)
		}
		fmt.Fprintf(&c.preActions, "\treturn true\nendfunction\n\n")
		var b strings.Builder
		fmt.Fprintf(&b, "if (%s()) then\n", fn)
		for _, child := range eca.Children {
			if child.Type != wtg.ECAAction || child.Group != 1 {
				continue
			}
			s, _ := c.convertECAToJASS(&child, triggerName, true)
			fmt.Fprintf(&b, "\t%s\n", s)
		}
		fmt.Fprintf(&b, "else\n")
		for _, child := range eca.Children {
			if child.Type != wtg.ECAAction || child.Group == 1 {
				continue
			}
			s, _ := c.convertECAToJASS(&child, triggerName, true)
			fmt.Fprintf(&b, "\t%s\n", s)
		}
		fmt.Fprintf(&b, "endif")
		return b.String(), nil
	}

	// ForLoopA / ForLoopAMultiple / ForLoopB / ForLoopBMultiple.
	if strings.HasPrefix(eca.Name, "ForLoopA") || strings.HasPrefix(eca.Name, "ForLoopB") {
		loopVar := "bj_forLoopAIndex"
		loopEnd := "bj_forLoopAIndexEnd"
		if strings.HasPrefix(eca.Name, "ForLoopB") {
			loopVar = "bj_forLoopBIndex"
			loopEnd = "bj_forLoopBIndexEnd"
		}
		startExpr, _ := c.resolveParameter(&eca.Parameters[0], triggerName, c.typeFor(eca.Name, 0), false)
		endExpr, _ := c.resolveParameter(&eca.Parameters[1], triggerName, c.typeFor(eca.Name, 1), false)
		var b strings.Builder
		fmt.Fprintf(&b, "set %s = %s\nset %s = %s\nloop\n\texitwhen %s > %s\n",
			loopVar, startExpr, loopEnd, endExpr, loopVar, loopEnd)
		if strings.HasSuffix(eca.Name, "Multiple") {
			for _, child := range eca.Children {
				s, _ := c.convertECAToJASS(&child, triggerName, true)
				fmt.Fprintf(&b, "\t%s\n", s)
			}
		} else {
			body, _ := c.resolveParameter(&eca.Parameters[2], triggerName, c.typeFor(eca.Name, 2), true)
			fmt.Fprintf(&b, "\t%s\n", body)
		}
		fmt.Fprintf(&b, "\tset %s = %s + 1\nendloop", loopVar, loopVar)
		return b.String(), nil
	}

	// ForLoopVar / ForLoopVarMultiple.
	if eca.Name == "ForLoopVar" || eca.Name == "ForLoopVarMultiple" {
		varExpr, _ := c.resolveParameter(&eca.Parameters[0], triggerName, "integer", false)
		startExpr, _ := c.resolveParameter(&eca.Parameters[1], triggerName, c.typeFor(eca.Name, 1), false)
		endExpr, _ := c.resolveParameter(&eca.Parameters[2], triggerName, c.typeFor(eca.Name, 2), false)
		var b strings.Builder
		fmt.Fprintf(&b, "set %s = %s\nloop\n\texitwhen %s > %s\n", varExpr, startExpr, varExpr, endExpr)
		if eca.Name == "ForLoopVarMultiple" {
			for _, child := range eca.Children {
				s, _ := c.convertECAToJASS(&child, triggerName, true)
				fmt.Fprintf(&b, "\t%s\n", s)
			}
		} else {
			body, _ := c.resolveParameter(&eca.Parameters[3], triggerName, c.typeFor(eca.Name, 3), true)
			fmt.Fprintf(&b, "\t%s\n", body)
		}
		fmt.Fprintf(&b, "\tset %s = %s + 1\nendloop", varExpr, varExpr)
		return b.String(), nil
	}

	// AndMultiple / OrMultiple — extract a boolean function, call it inline.
	if eca.Name == "AndMultiple" || eca.Name == "OrMultiple" {
		fn := c.fnName(triggerName)
		var conds []string
		for _, child := range eca.Children {
			s, _ := c.convertECAToJASS(&child, triggerName, false)
			conds = append(conds, s)
		}
		fmt.Fprintf(&c.preActions, "function %s takes nothing returns boolean\n", fn)
		if eca.Name == "AndMultiple" {
			for _, cnd := range conds {
				fmt.Fprintf(&c.preActions, "\tif (not(%s)) then\n\t\treturn false\n\tendif\n", cnd)
			}
			fmt.Fprintf(&c.preActions, "\treturn true\nendfunction\n\n")
		} else {
			for _, cnd := range conds {
				fmt.Fprintf(&c.preActions, "\tif (%s) then\n\t\treturn true\n\tendif\n", cnd)
			}
			fmt.Fprintf(&c.preActions, "\treturn false\nendfunction\n\n")
		}
		return fn + "()", nil
	}

	// SetVariable — assignment. Always a statement: `set lhs = rhs`.
	if eca.Name == "SetVariable" {
		var varType string
		for _, v := range c.in.Triggers.Variables {
			if v.Name == eca.Parameters[0].Value {
				varType = v.Type
				break
			}
		}
		lhs, _ := c.resolveParameter(&eca.Parameters[0], triggerName, "", false)
		rhs, _ := c.resolveParameter(&eca.Parameters[1], triggerName, varType, false)
		return fmt.Sprintf("set %s = %s", lhs, rhs), nil
	}

	// CommentString — JASS line comment.
	if eca.Name == "CommentString" {
		body, _ := c.resolveParameter(&eca.Parameters[0], triggerName, "", false)
		return "// " + strings.TrimSpace(body), nil
	}

	// CustomScriptCode — inline the raw JASS verbatim. In a JASS map this is
	// exactly the language we're emitting, so it drops in cleanly (unlike the
	// Lua path, where JASS custom-script is inlined into a .lua file).
	if eca.Name == "CustomScriptCode" {
		v, _ := c.resolveParameter(&eca.Parameters[0], triggerName, "", false)
		if strings.HasPrefix(v, `"`) && strings.HasSuffix(v, `"`) {
			v = strings.TrimSuffix(strings.TrimPrefix(v, `"`), `"`)
			v = strings.ReplaceAll(v, `\\`, `\`)
		}
		return v, nil
	}

	// Resolve all parameter slots for the remaining branches.
	resolved := make([]string, len(eca.Parameters))
	for i := range eca.Parameters {
		typ := c.typeFor(eca.Name, i)
		v, _ := c.resolveParameter(&eca.Parameters[i], triggerName, typ, false)
		resolved[i] = v
	}

	// Any other *Multiple — closure-wrapped body passed as a `code` callback.
	if strings.HasSuffix(eca.Name, "Multiple") {
		scriptName := c.scriptNameFor(eca.Name)
		if strings.HasPrefix(scriptName, "_"+eca.Name+"_") {
			scriptName = scriptName[len("_"+eca.Name+"_"):]
		}
		fn := c.fnName(triggerName)
		fmt.Fprintf(&c.preActions, "function %s takes nothing returns nothing\n", fn)
		for _, child := range eca.Children {
			s, _ := c.convertECAToJASS(&child, triggerName, true)
			fmt.Fprintf(&c.preActions, "\t%s\n", s)
		}
		fmt.Fprintf(&c.preActions, "endfunction\n\n")
		var expr string
		if eca.Name == "EnumDestructablesInCircleBJMultiple" {
			expr = fmt.Sprintf("%s(%s, %s, function %s)", scriptName, resolved[0], resolved[1], fn)
		} else {
			expr = fmt.Sprintf("%s(%s, function %s)", scriptName, resolved[0], fn)
		}
		return jassCall(addCall, expr), nil
	}

	// WaitForCondition — loop with a 0.1s tick.
	if eca.Name == "WaitForCondition" {
		return fmt.Sprintf("loop\n\texitwhen %s\n\tcall TriggerSleepAction(RMaxBJ(bj_WAIT_FOR_COND_MIN_INTERVAL, %s))\nendloop", resolved[0], resolved[1]), nil
	}

	// OperatorCompare* / OperatorInt / OperatorReal — binary operator. JASS
	// uses `!=` directly (no Lua `~=` substitution).
	if strings.HasPrefix(eca.Name, "OperatorCompare") || eca.Name == "OperatorInt" || eca.Name == "OperatorReal" {
		return fmt.Sprintf("%s %s %s", resolved[0], resolved[1], resolved[2]), nil
	}

	// OperatorString — JASS string concat is `+`.
	if eca.Name == "OperatorString" {
		return fmt.Sprintf("(%s + %s)", resolved[0], resolved[1]), nil
	}

	// AddTriggerEvent — inject param[0] (the trigger var) as the first arg of
	// param[1]'s event-bind call.
	if eca.Name == "AddTriggerEvent" {
		s := resolved[1]
		idx := strings.IndexByte(s, '(')
		if idx == -1 {
			return jassCall(addCall, resolved[1]), nil
		}
		return jassCall(addCall, s[:idx+1]+resolved[0]+", "+s[idx+1:]), nil
	}

	// Generic fall-through. boolexpr/boolcall/code slots get a per-slot helper
	// function. JASS idiom: `code` and `boolexpr` pass `function f` (boolexpr
	// wrapped in Condition()); `boolcall` calls inline.
	var args strings.Builder
	for k := range eca.Parameters {
		t := c.typeFor(eca.Name, k)
		switch t {
		case "boolexpr":
			fn := c.fnName(triggerName)
			fmt.Fprintf(&c.preActions, "function %s takes nothing returns boolean\n\treturn %s\nendfunction\n\n", fn, resolved[k])
			args.WriteString("Condition(function " + fn + ")")
		case "boolcall":
			fn := c.fnName(triggerName)
			fmt.Fprintf(&c.preActions, "function %s takes nothing returns boolean\n\treturn %s\nendfunction\n\n", fn, resolved[k])
			args.WriteString(fn + "()")
		case "code":
			fn := c.fnName(triggerName)
			code, _ := c.resolveParameter(&eca.Parameters[k], triggerName, t, true)
			fmt.Fprintf(&c.preActions, "function %s takes nothing returns nothing\n\t%s\nendfunction\n\n", fn, code)
			args.WriteString("function " + fn)
		default:
			args.WriteString(resolved[k])
		}
		if k < len(eca.Parameters)-1 {
			args.WriteString(", ")
		}
	}
	scriptName := c.scriptNameFor(eca.Name)
	return jassCall(addCall, scriptName+"("+args.String()+")"), nil
}
