package w3e

import (
	"math"
	"os"
	"path/filepath"
	"testing"
)

// Committed, self-contained terrain fixtures. These are generated by
// constructing minimal w3e.File values and round-tripping them through
// w3e.Encode (see internal/formats/w3e/testdata/README.md), so they carry
// NO real-map data and live in-repo — the byte-for-byte round-trip tests
// below RUN on a clean checkout instead of Skipf'ing on an out-of-repo path.
// Two fixtures cover both wire layouts: v12 (Reforged, 8 B/vertex) and v11
// (Classic/TFT, 7 B/vertex).
var (
	fixtureV12 = filepath.Join("testdata", "reforged_v12.w3e")
	fixtureV11 = filepath.Join("testdata", "classic_v11.w3e")
)

// fixturePath is the canonical small fixture used by the parse sanity test.
var fixturePath = fixtureV12

func TestParse_v1_6(t *testing.T) {
	data, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("read fixture %q: %v", fixturePath, err)
	}

	f, err := Parse(data)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}

	// Format magic must be "W3E!".
	if f.Format != Magic {
		t.Errorf("format = %q, want %q", f.Format[:], Magic[:])
	}

	// Dimensions: the committed reforged_v12 fixture is a small square grid
	// (9×9 vertices = an 8-tile span). The on-wire vertex count per axis is
	// `tile_count + 1`. We don't hard-code "9" beyond the basic invariants —
	// the playable tile count is stored separately in war3map.w3i, so .w3e is
	// just the heightfield grid. These invariants hold for any real terrain too.
	if f.Width != f.Height {
		t.Errorf("expected square map, got %dx%d", f.Width, f.Height)
	}
	if f.Width < 4 || f.Width > 1024 {
		t.Errorf("dimension %d outside sane bounds [4, 1024]", f.Width)
	}

	// Tile slice length must match width*height (row-major).
	wantTiles := int(f.Width) * int(f.Height)
	if got := len(f.Tiles); got != wantTiles {
		t.Fatalf("Tiles len = %d, want %d (= Width*Height)", got, wantTiles)
	}

	// CenterOffset is the game-coord position of vertex (0,0) — the
	// bottom-left of the map. It must be a finite float that round-tripped
	// through the float32 wire encoding exactly. The fixture uses (-512,-512);
	// we assert finiteness + exact round-trip rather than a specific value so
	// the test isn't pinned to one map's dimensions.
	if math.IsNaN(float64(f.CenterOffset[0])) || math.IsInf(float64(f.CenterOffset[0]), 0) ||
		math.IsNaN(float64(f.CenterOffset[1])) || math.IsInf(float64(f.CenterOffset[1]), 0) {
		t.Errorf("CenterOffset = %v, want finite", f.CenterOffset)
	}

	// FourCC tileset slot validation: at least one ground entry, all 4 chars.
	if len(f.GroundTilesets) == 0 {
		t.Errorf("no ground tilesets")
	}
	for i, id := range f.GroundTilesets {
		if len(id) != 4 {
			t.Errorf("GroundTilesets[%d] = %q (len %d), want 4-char FourCC", i, id, len(id))
		}
	}
	for i, id := range f.CliffTilesets {
		if len(id) != 4 {
			t.Errorf("CliffTilesets[%d] = %q (len %d), want 4-char FourCC", i, id, len(id))
		}
	}

	// Sample tilepoints: corners + center. We touch each helper to verify
	// the bit-unpack math compiles and doesn't panic on edge values.
	w, h := int(f.Width), int(f.Height)
	idx := func(col, row int) int { return row*w + col }
	type sample struct {
		name     string
		col, row int
	}
	samples := []sample{
		{"bottom-left", 0, 0},
		{"bottom-right", w - 1, 0},
		{"top-left", 0, h - 1},
		{"top-right", w - 1, h - 1},
		{"center", w / 2, h / 2},
	}
	for _, s := range samples {
		tp := f.Tiles[idx(s.col, s.row)]
		// Exercise every helper at least once so a future bit-fiddling
		// regression doesn't sneak past this test.
		_ = tp.Z()
		_ = tp.WaterZ()
		_ = tp.GroundTexIdx()
		_ = tp.CliffTexIdx()
		_ = tp.HasRamp()
		_ = tp.HasBlight()
		_ = tp.HasWater()
		_ = tp.HasBoundary()
	}

	// Visual sanity dump — only printed with `go test -v`.
	t.Logf("war3map.w3e fixture: version=%d tileset=%q custom=%v dims=%dx%d offset=(%.1f,%.1f)",
		f.Version, string(f.Tileset), f.CustomTileset,
		f.Width, f.Height, f.CenterOffset[0], f.CenterOffset[1])
	t.Logf("ground tilesets (%d): %v", len(f.GroundTilesets), f.GroundTilesets)
	t.Logf("cliff  tilesets (%d): %v", len(f.CliffTilesets), f.CliffTilesets)
	for _, s := range samples {
		tp := f.Tiles[idx(s.col, s.row)]
		gameX := f.CenterOffset[0] + float32(s.col)*128
		gameY := f.CenterOffset[1] + float32(s.row)*128
		t.Logf("  %-13s (col=%2d row=%2d game=(%7.1f,%7.1f)) z=%6.2f waterZ=%6.2f gtex=%d ctex=%d layer=%d var=%d flags=0b%04b boundary=%v",
			s.name, s.col, s.row, gameX, gameY,
			tp.Z(), tp.WaterZ(),
			tp.GroundTexIdx(), tp.CliffTexIdx(),
			tp.LayerHeight, tp.TextureDetails,
			tp.Flags, tp.Boundary)
	}
}
