// Local shim for Wails bindings that ship in Go but aren't yet visible in
// the autogenerated frontend/wailsjs/* surface. Wails regenerates that
// surface on every `wails build` — until that runs, the new App methods
// only exist on the runtime `window.go.main.App` object.
//
// We declare them here so the Object Editor's TypeScript stays type-safe
// without forcing a wails-bindings regeneration step into the agent's
// build loop. After the first `wails build`, these can collapse to
// re-exports from `../wailsjs/go/main/App.js`.

import type { main } from '../wailsjs/go/models'

// Object-editor kind tag. Wire-stable across Go + JS — adding a new kind
// here MUST be paired with a Go-side registerObjectKind in handlers.go.
export type ObjectKind =
  | 'units'
  | 'items'
  | 'abilities'
  | 'buffs'
  | 'destructables'
  | 'doodads'
  | 'upgrades'

interface WailsApp {
  // Phase-1b units-typed surface kept as backwards-compat aliases.
  SetUnitObjectField: (id: string, column: string, value: string) => Promise<main.UnitObjectDetail>
  CreateCustomUnit: (baseID: string, id: string) => Promise<CreateCustomUnitResult>
  DeleteCustomUnit: (id: string) => Promise<void>
  // Phase-2b generic surface. Same return shapes — the UnitObjectListEntity
  // / UnitObjectDetail types serve every kind.
  ListObjects: (kind: ObjectKind) => Promise<main.UnitObjectListEntity[]>
  GetObject: (kind: ObjectKind, id: string) => Promise<main.UnitObjectDetail | null>
  SetObjectField: (kind: ObjectKind, id: string, column: string, value: string) => Promise<main.UnitObjectDetail>
  CreateCustomObject: (kind: ObjectKind, baseID: string, id: string) => Promise<CreateCustomObjectResult>
  DeleteCustomObject: (kind: ObjectKind, id: string) => Promise<void>
  // Phase-3 polish.
  ConvertObject: (srcKind: ObjectKind, srcID: string, dstKind: ObjectKind) => Promise<ConvertObjectResult>
  ListCommandButtons: () => Promise<CommandButtonEntry[]>
}

// The Wails autobind surface — populated by the Go side at startup, so it
// exists by the time any Svelte component mounts.
function app(): WailsApp {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (window as any).go?.main?.App as WailsApp
}

export interface CreateCustomUnitResult {
  id: string
  detail: main.UnitObjectDetail
}

export interface CreateCustomObjectResult {
  id: string
  detail: main.UnitObjectDetail
}

export function SetUnitObjectField(
  id: string,
  column: string,
  value: string,
): Promise<main.UnitObjectDetail> {
  return app().SetUnitObjectField(id, column, value)
}

export function CreateCustomUnit(
  baseID: string,
  id: string,
): Promise<CreateCustomUnitResult> {
  return app().CreateCustomUnit(baseID, id)
}

export function DeleteCustomUnit(id: string): Promise<void> {
  return app().DeleteCustomUnit(id)
}

// Generic Phase-2b helpers. Default to type-safety via the ObjectKind union
// so a typo in the caller fails at compile time.

export function ListObjects(
  kind: ObjectKind,
): Promise<main.UnitObjectListEntity[]> {
  return app().ListObjects(kind)
}

export function GetObject(
  kind: ObjectKind,
  id: string,
): Promise<main.UnitObjectDetail | null> {
  return app().GetObject(kind, id)
}

export function SetObjectField(
  kind: ObjectKind,
  id: string,
  column: string,
  value: string,
): Promise<main.UnitObjectDetail> {
  return app().SetObjectField(kind, id, column, value)
}

export function CreateCustomObject(
  kind: ObjectKind,
  baseID: string,
  id: string,
): Promise<CreateCustomObjectResult> {
  return app().CreateCustomObject(kind, baseID, id)
}

export function DeleteCustomObject(
  kind: ObjectKind,
  id: string,
): Promise<void> {
  return app().DeleteCustomObject(kind, id)
}

// Phase 3 — cross-kind conversion. Currently only doodads↔destructables is
// accepted on the Go side; other pairs return an error.
export interface ConvertObjectResult {
  id: string
  detail: main.UnitObjectDetail | null
}

export function ConvertObject(
  srcKind: ObjectKind,
  srcID: string,
  dstKind: ObjectKind,
): Promise<ConvertObjectResult> {
  return app().ConvertObject(srcKind, srcID, dstKind)
}

// Phase 3 — icon picker. ListCommandButtons enumerates BLP icons under
// CASC's replaceabletextures/commandbuttons/ prefix. Cached per-process by
// the Go side so subsequent calls are O(1).
export interface CommandButtonEntry {
  path: string // full asset path, lowercase, forward-slash
  name: string // basename without extension (e.g. "BTNFootman")
}

export function ListCommandButtons(): Promise<CommandButtonEntry[]> {
  return app().ListCommandButtons()
}
