// Local shim for Wails bindings that ship in Go but aren't yet visible in
// the autogenerated frontend/wailsjs/* surface. Wails regenerates that
// surface on every `wails build` — until that runs, the new App methods
// only exist on the runtime `window.go.main.App` object.
//
// We declare them here so the Object Editor's TypeScript stays type-safe
// without forcing a wails-bindings regeneration step into the agent's
// build loop. After the first `wails build`, these can collapse to
// re-exports from `../wailsjs/go/main/App.js`.

import type { main } from '../wailsjs/go/models'

interface WailsApp {
  SetUnitObjectField: (id: string, column: string, value: string) => Promise<main.UnitObjectDetail>
  CreateCustomUnit: (baseID: string, id: string) => Promise<CreateCustomUnitResult>
  DeleteCustomUnit: (id: string) => Promise<void>
}

// The Wails autobind surface — populated by the Go side at startup, so it
// exists by the time any Svelte component mounts.
function app(): WailsApp {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (window as any).go?.main?.App as WailsApp
}

export interface CreateCustomUnitResult {
  id: string
  detail: main.UnitObjectDetail
}

export function SetUnitObjectField(
  id: string,
  column: string,
  value: string,
): Promise<main.UnitObjectDetail> {
  return app().SetUnitObjectField(id, column, value)
}

export function CreateCustomUnit(
  baseID: string,
  id: string,
): Promise<CreateCustomUnitResult> {
  return app().CreateCustomUnit(baseID, id)
}

export function DeleteCustomUnit(id: string): Promise<void> {
  return app().DeleteCustomUnit(id)
}
