// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSelection() {
  return window['go']['main']['App']['ClearSelection']();
}

export function CloseMap() {
  return window['go']['main']['App']['CloseMap']();
}

export function GetDoodad(arg1) {
  return window['go']['main']['App']['GetDoodad'](arg1);
}

export function GetDoodadTypeIndex() {
  return window['go']['main']['App']['GetDoodadTypeIndex']();
}

export function GetMapBytes() {
  return window['go']['main']['App']['GetMapBytes']();
}

export function GetPathingMap() {
  return window['go']['main']['App']['GetPathingMap']();
}

export function GetReforgedMode() {
  return window['go']['main']['App']['GetReforgedMode']();
}

export function GetSelection() {
  return window['go']['main']['App']['GetSelection']();
}

export function GetTerrain() {
  return window['go']['main']['App']['GetTerrain']();
}

export function GetUnit(arg1) {
  return window['go']['main']['App']['GetUnit'](arg1);
}

export function GetUnitTypeIndex() {
  return window['go']['main']['App']['GetUnitTypeIndex']();
}

export function IsDirty() {
  return window['go']['main']['App']['IsDirty']();
}

export function ListDoodads() {
  return window['go']['main']['App']['ListDoodads']();
}

export function ListUnits() {
  return window['go']['main']['App']['ListUnits']();
}

export function LogJS(arg1) {
  return window['go']['main']['App']['LogJS'](arg1);
}

export function MoveUnit(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveUnit'](arg1, arg2, arg3, arg4);
}

export function OpenMap(arg1) {
  return window['go']['main']['App']['OpenMap'](arg1);
}

export function OpenMapDialog() {
  return window['go']['main']['App']['OpenMapDialog']();
}

export function SaveMap() {
  return window['go']['main']['App']['SaveMap']();
}

export function SelectUnit(arg1) {
  return window['go']['main']['App']['SelectUnit'](arg1);
}

export function SetReforgedMode(arg1) {
  return window['go']['main']['App']['SetReforgedMode'](arg1);
}

export function SetSelection(arg1) {
  return window['go']['main']['App']['SetSelection'](arg1);
}

export function SetUnitAnimation(arg1, arg2) {
  return window['go']['main']['App']['SetUnitAnimation'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
