// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {doodadsdoo} from '../models';
import {unitsdoo} from '../models';
import {forge} from '../models';
import {w3i} from '../models';

export function BeginUndoGroup(arg1:string):Promise<void>;

export function CanRedo():Promise<boolean>;

export function CanUndo():Promise<boolean>;

export function ClearSelection():Promise<main.SelectionDTO>;

export function CloseMap():Promise<main.MapStatus>;

export function EmitTestCommand(arg1:string):Promise<void>;

export function EndUndoGroup():Promise<void>;

export function ForceQuit():Promise<void>;

export function GetBridgeInfo():Promise<main.BridgeInfo>;

export function GetDoodad(arg1:number):Promise<doodadsdoo.Doodad>;

export function GetDoodadTypeIndex():Promise<Record<string, main.DoodadTypeInfo>>;

export function GetMapBytes():Promise<string>;

export function GetMinimapBytes():Promise<main.MinimapDTO>;

export function GetPathingMap():Promise<main.PathingMapDTO>;

export function GetReforgedMode():Promise<boolean>;

export function GetSelection():Promise<main.SelectionDTO>;

export function GetTerrain():Promise<main.TerrainDTO>;

export function GetUnit(arg1:number):Promise<unitsdoo.Entity>;

export function GetUnitTypeIndex():Promise<Record<string, main.UnitTypeInfo>>;

export function HistoryList():Promise<forge.HistoryState>;

export function IsDirty():Promise<boolean>;

export function LaunchInWC3():Promise<void>;

export function ListDoodads():Promise<Array<main.DoodadDTO>>;

export function ListUnits():Promise<Array<main.UnitDTO>>;

export function LogJS(arg1:string):Promise<void>;

export function MapInfoApply(arg1:Record<string, any>):Promise<void>;

export function MapInfoGet():Promise<w3i.Info>;

export function MoveDoodad(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function MoveUnit(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function OpenMap(arg1:string):Promise<main.MapStatus>;

export function OpenMapDialog():Promise<string>;

export function Redo():Promise<void>;

export function RotateDoodad(arg1:number,arg2:number):Promise<void>;

export function RotateUnit(arg1:number,arg2:number):Promise<void>;

export function SaveMap():Promise<void>;

export function ScaleDoodad(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function ScaleUnit(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SelectUnit(arg1:number):Promise<main.SelectionDTO>;

export function SetReforgedMode(arg1:boolean):Promise<boolean>;

export function SetSelection(arg1:Array<main.SelectionItemDTO>):Promise<main.SelectionDTO>;

export function SetUnitAnimation(arg1:number,arg2:string):Promise<void>;

export function Status():Promise<main.MapStatus>;

export function Undo():Promise<void>;

export function ListTilesets():Promise<Array<main.TilesetInfoDTO>>;

export function SwapTileset(arg1:main.SwapTilesetRequest):Promise<main.TerrainDTO>;
