// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearSelection():Promise<main.SelectionDTO>;

export function CloseMap():Promise<main.MapStatus>;

export function GetSelection():Promise<main.SelectionDTO>;

export function GetTerrain():Promise<main.TerrainDTO>;

export function ListUnits():Promise<Array<main.UnitDTO>>;

export function OpenMap(arg1:string):Promise<main.MapStatus>;

export function OpenMapDialog():Promise<string>;

export function SelectUnit(arg1:number):Promise<main.SelectionDTO>;

export function SetSelection(arg1:Array<main.SelectionItemDTO>):Promise<main.SelectionDTO>;

export function Status():Promise<main.MapStatus>;
