// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseMap() {
  return window['go']['main']['App']['CloseMap']();
}

export function ListUnits() {
  return window['go']['main']['App']['ListUnits']();
}

export function OpenMap(arg1) {
  return window['go']['main']['App']['OpenMap'](arg1);
}

export function OpenMapDialog() {
  return window['go']['main']['App']['OpenMapDialog']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
