// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommentTrigger(arg1, arg2) {
  return window['go']['main']['App']['AddCommentTrigger'](arg1, arg2);
}

export function AddGUITrigger(arg1, arg2) {
  return window['go']['main']['App']['AddGUITrigger'](arg1, arg2);
}

export function AddScriptTrigger(arg1, arg2) {
  return window['go']['main']['App']['AddScriptTrigger'](arg1, arg2);
}

export function AddTriggerCategory(arg1, arg2) {
  return window['go']['main']['App']['AddTriggerCategory'](arg1, arg2);
}

export function AddTriggerVariable(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddTriggerVariable'](arg1, arg2, arg3, arg4, arg5);
}

export function BeginUndoGroup(arg1) {
  return window['go']['main']['App']['BeginUndoGroup'](arg1);
}

export function CanRedo() {
  return window['go']['main']['App']['CanRedo']();
}

export function CanUndo() {
  return window['go']['main']['App']['CanUndo']();
}

export function ClearSelection() {
  return window['go']['main']['App']['ClearSelection']();
}

export function CloseMap() {
  return window['go']['main']['App']['CloseMap']();
}

export function ConvertObject(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertObject'](arg1, arg2, arg3);
}

export function CreateCustomObject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCustomObject'](arg1, arg2, arg3);
}

export function CreateCustomUnit(arg1, arg2) {
  return window['go']['main']['App']['CreateCustomUnit'](arg1, arg2);
}

export function DeleteCustomObject(arg1, arg2) {
  return window['go']['main']['App']['DeleteCustomObject'](arg1, arg2);
}

export function DeleteCustomUnit(arg1) {
  return window['go']['main']['App']['DeleteCustomUnit'](arg1);
}

export function DeleteTriggerNode(arg1) {
  return window['go']['main']['App']['DeleteTriggerNode'](arg1);
}

export function DiscardTo(arg1) {
  return window['go']['main']['App']['DiscardTo'](arg1);
}

export function EmitTestCommand(arg1) {
  return window['go']['main']['App']['EmitTestCommand'](arg1);
}

export function EndUndoGroup() {
  return window['go']['main']['App']['EndUndoGroup']();
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GameplayConstantsApply(arg1) {
  return window['go']['main']['App']['GameplayConstantsApply'](arg1);
}

export function GameplayConstantsGet() {
  return window['go']['main']['App']['GameplayConstantsGet']();
}

export function GetBridgeInfo() {
  return window['go']['main']['App']['GetBridgeInfo']();
}

export function GetDoodad(arg1) {
  return window['go']['main']['App']['GetDoodad'](arg1);
}

export function GetDoodadTypeIndex() {
  return window['go']['main']['App']['GetDoodadTypeIndex']();
}

export function GetMapBytes() {
  return window['go']['main']['App']['GetMapBytes']();
}

export function GetMinimapBytes() {
  return window['go']['main']['App']['GetMinimapBytes']();
}

export function GetObject(arg1, arg2) {
  return window['go']['main']['App']['GetObject'](arg1, arg2);
}

export function GetPathingMap() {
  return window['go']['main']['App']['GetPathingMap']();
}

export function GetReforgedMode() {
  return window['go']['main']['App']['GetReforgedMode']();
}

export function GetSelection() {
  return window['go']['main']['App']['GetSelection']();
}

export function GetTerrain() {
  return window['go']['main']['App']['GetTerrain']();
}

export function GetTrigger(arg1) {
  return window['go']['main']['App']['GetTrigger'](arg1);
}

export function GetTriggerFunctionsMeta() {
  return window['go']['main']['App']['GetTriggerFunctionsMeta']();
}

export function GetUnit(arg1) {
  return window['go']['main']['App']['GetUnit'](arg1);
}

export function GetUnitObject(arg1) {
  return window['go']['main']['App']['GetUnitObject'](arg1);
}

export function GetUnitTypeIndex() {
  return window['go']['main']['App']['GetUnitTypeIndex']();
}

export function HistoryList() {
  return window['go']['main']['App']['HistoryList']();
}

export function HistoryUndoCount() {
  return window['go']['main']['App']['HistoryUndoCount']();
}

export function IsDirty() {
  return window['go']['main']['App']['IsDirty']();
}

export function LaunchInWC3() {
  return window['go']['main']['App']['LaunchInWC3']();
}

export function ListCommandButtons() {
  return window['go']['main']['App']['ListCommandButtons']();
}

export function ListDoodads() {
  return window['go']['main']['App']['ListDoodads']();
}

export function ListObjects(arg1) {
  return window['go']['main']['App']['ListObjects'](arg1);
}

export function ListSkyModels() {
  return window['go']['main']['App']['ListSkyModels']();
}

export function ListTilesets() {
  return window['go']['main']['App']['ListTilesets']();
}

export function ListTriggerTree() {
  return window['go']['main']['App']['ListTriggerTree']();
}

export function ListUnitObjects() {
  return window['go']['main']['App']['ListUnitObjects']();
}

export function ListUnits() {
  return window['go']['main']['App']['ListUnits']();
}

export function LogJS(arg1) {
  return window['go']['main']['App']['LogJS'](arg1);
}

export function MapInfoApply(arg1) {
  return window['go']['main']['App']['MapInfoApply'](arg1);
}

export function MapInfoGet() {
  return window['go']['main']['App']['MapInfoGet']();
}

export function MoveDoodad(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveDoodad'](arg1, arg2, arg3, arg4);
}

export function MoveTriggerNode(arg1, arg2) {
  return window['go']['main']['App']['MoveTriggerNode'](arg1, arg2);
}

export function MoveUnit(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveUnit'](arg1, arg2, arg3, arg4);
}

export function NewWindow() {
  return window['go']['main']['App']['NewWindow']();
}

export function OpenMap(arg1) {
  return window['go']['main']['App']['OpenMap'](arg1);
}

export function OpenMapDialog() {
  return window['go']['main']['App']['OpenMapDialog']();
}

export function OpenMapFileDialog() {
  return window['go']['main']['App']['OpenMapFileDialog']();
}

export function OpenMapInNewWindow(arg1) {
  return window['go']['main']['App']['OpenMapInNewWindow'](arg1);
}

export function Redo() {
  return window['go']['main']['App']['Redo']();
}

export function RenameTriggerNode(arg1, arg2) {
  return window['go']['main']['App']['RenameTriggerNode'](arg1, arg2);
}

export function RotateDoodad(arg1, arg2) {
  return window['go']['main']['App']['RotateDoodad'](arg1, arg2);
}

export function RotateUnit(arg1, arg2) {
  return window['go']['main']['App']['RotateUnit'](arg1, arg2);
}

export function SaveMap() {
  return window['go']['main']['App']['SaveMap']();
}

export function ScaleDoodad(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScaleDoodad'](arg1, arg2, arg3, arg4);
}

export function ScaleUnit(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScaleUnit'](arg1, arg2, arg3, arg4);
}

export function SelectUnit(arg1) {
  return window['go']['main']['App']['SelectUnit'](arg1);
}

export function SetMapHeaderScript(arg1) {
  return window['go']['main']['App']['SetMapHeaderScript'](arg1);
}

export function SetObjectField(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetObjectField'](arg1, arg2, arg3, arg4);
}

export function SetReforgedMode(arg1) {
  return window['go']['main']['App']['SetReforgedMode'](arg1);
}

export function SetSelection(arg1) {
  return window['go']['main']['App']['SetSelection'](arg1);
}

export function SetSkyModel(arg1) {
  return window['go']['main']['App']['SetSkyModel'](arg1);
}

export function SetTriggerCustomText(arg1, arg2) {
  return window['go']['main']['App']['SetTriggerCustomText'](arg1, arg2);
}

export function SetTriggerDescription(arg1, arg2) {
  return window['go']['main']['App']['SetTriggerDescription'](arg1, arg2);
}

export function SetTriggerEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetTriggerEnabled'](arg1, arg2);
}

export function SetTriggerInitiallyOn(arg1, arg2) {
  return window['go']['main']['App']['SetTriggerInitiallyOn'](arg1, arg2);
}

export function SetTriggerRunOnInit(arg1, arg2) {
  return window['go']['main']['App']['SetTriggerRunOnInit'](arg1, arg2);
}

export function SetTriggerVariable(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SetTriggerVariable'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetUnitAnimation(arg1, arg2) {
  return window['go']['main']['App']['SetUnitAnimation'](arg1, arg2);
}

export function SetUnitObjectField(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetUnitObjectField'](arg1, arg2, arg3);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function SwapTileset(arg1) {
  return window['go']['main']['App']['SwapTileset'](arg1);
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}

export function UndoTo(arg1) {
  return window['go']['main']['App']['UndoTo'](arg1);
}
